# Generated by Django 4.2 on 2023-05-04 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("complement", models.CharField(max_length=50, null=True)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=50)),
                ("neighborhood", models.CharField(max_length=50)),
            ],
        ),
    ]
