# Generated by Django 4.2 on 2023-05-02 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(null=True)),
                ("price", models.FloatField()),
                ("is_available", models.BooleanField()),
                ("category", models.CharField(max_length=50)),
            ],
        ),
    ]
