# Generated by Django 4.2 on 2023-05-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="category",
            new_name="seller_id",
        ),
        migrations.RemoveField(
            model_name="order",
            name="description",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("realizado", "Pedido Realizado"),
                    ("andamento", "Em Andamento"),
                    ("entregue", "Entregue"),
                ],
                default="realizado",
                max_length=30,
            ),
        ),
    ]
