# Generated by Django 4.2 on 2023-05-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcart",
            name="values",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
